class Bike{
  String? nameone,nametwo,namethree,namefour,namefive,namesix,nameseven,nameeight,namenine,nameten;
  int? yearone,yeartwo,yearthree,yearfour,yearfive,yearsix,yearseven,yeareight,yearnine,yearten;
  int? revenueone,revenuetwo,revenuethree,revenuefour,revenuefive,revenuesix,revenueseven,revenueeight,revenuenine,revenueten;
  int? countryone,countrytwo,countrythree,countryfour,countryfive,countrysix,countryseven,countryeight,countrynine,countryten;
  int? productone,producttwo,productthree,productfour,productfive,productsix,productseven,producteight,productnine,productten;
  void display(){
    print('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>');
    print('**********DETAILS OF THE TOP TEN BIKES OF THE WORLD*********');
    print('<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<>>>>>>>>>>>>>>>>>>>>>>>>>>>>>');
    print('<<<<<<<<<<<<<<<<<<<DETAILS OF THE 1st BIKE>>>>>>>>>>>>>>>>>>');
    print('The name of the bike company:$nameone');
    print('The company was manufactured in the year:$yearone');
    print('The revenue of the company in dollars:$revenueone');
    print('The company has production plants in countries:$countryone');
    print('The company has total production plants worldwide:$productone');
    print('<<<<<<<<DETAILS OF THE 2nd BIKE>>>>>>>>>>');
    print('The name of the bike company:$nametwo');
    print('The company was manufactured in the year:$yeartwo');
    print('The revenue of the company in dollars:$revenuetwo');
    print('The company has production plants in countries:$countrytwo');
    print('The company has total production plants worldwide:$producttwo');
    print('<<<<<<<<DETAILS OF THE 3rd BIKE>>>>>>>>>>');
    print('The name of the bike company:$namethree');
    print('The company was manufactured  in the year:$yearthree');
    print('The revenue of the company in dollars:$revenuethree');
    print('The company has production plants in countries:$countrythree');
    print('The company has total production plants worldwide:$productthree');
    print('<<<<<<<<DETAILS OF THE 4th BIKE>>>>>>>>>>>');
    print('The name of the bike comapny:$namefour');
    print('The company was manufactured  in the year:$yearfour');
    print('The revenue of the company in dollars:$revenuefour');
    print('The company has production plants in countries:$countryfour');
    print('The company has total production plants worldwide:$productfour');
    print('<<<<<<<<DETAILS OF THE 5th BIKE>>>>>>>>>>>');
    print('The name of the bike company:$namefive');
    print('The company was manufactured  in the year:$yearfive');
    print('The revenue of the company in dollars:$revenuefive');
    print('The company has production plants in countries:$countryfive');
    print('The company has total production plants worldwide:$productfive');
    print('<<<<<<<<DETAILS OF THE 6th BIKE>>>>>>>>>>>');
    print('The name of the bike company:$namesix');
    print('The company was manufactured in the year:$yearsix');
    print('The revenue of the company in dollars:$revenuesix');
    print('The company has production plants in countries:$countrysix');
    print('The company has total production plants worldwide:$productsix');
    print('<<<<<<<<DETAILS OF THE 7th BIKE>>>>>>>>>>>');
    print('The name of the bike company:$nameseven');
    print('The company was manufactured in the year:$yearseven');
    print('The revenue of the company in dollars:$revenueseven');
    print('The company has production plants in countries:$countryseven');
    print('The company has total production plants worldwide:$productseven');
    print('<<<<<<<<DETAILS OF THE 8th BIKE>>>>>>>>>>>');
    print('The name of the bike comapny:$nameeight');
    print('The company was manufactured  in the year:$yeareight');
    print('The revenue of the company in dollars:$revenueeight');
    print('The company has production plants in countries:$countryeight');
    print('The company has total production plants worldwide:$producteight');
    print('<<<<<<<<DETAILS OF THE 9th BIKE>>>>>>>>>>>');
    print('The name of the bike company:$namenine');
    print('The company was manufactured  in the year:$yearnine');
    print('The revenue of the company in dollars:$revenuenine');
    print('The company has production plants in countries:$countrynine');
    print('The company has total production plants worldwide:$productnine');
    print('<<<<<<<<DETAILS OF THE 10th BIKE>>>>>>>>>>');
    print('The name of the bike company:$nameten');
    print('The company was manufactured  in the year:$yearten');
    print('The revenue of the company in dollars:$revenueten');
    print('The company has production plants in countries:$countryten');
    print('The company has toatl production plants worldwide:$productten');
  }
}
void main()
{
  Bike b=Bike();
  b.nameone='HONDA';
  b.nametwo='HARLEY DAVIDSON';
  b.namethree='BAJAJ AUTO';
  b.namefour='HERO MOTO CORP';
  b.namefive='KTM';
  b.namesix='TVS';
  b.nameseven='BMW';
  b.nameeight='PIAGGIO';
  b.namenine='ROYAL ENFIELD';
  b.nameten='SUZUKI';
  b.yearone=1960;
  b.yeartwo=1903;
  b.yearthree=1970;
  b.yearfour=1937;
  b.yearfive=1969;
  b.yearsix=1901;
  b.yearseven=1920;
  b.yeareight=1995;
  b.yearnine=1999;
  b.yearten=1945;
  b.revenueone=163000;
  b.revenuetwo=57000;
  b.revenuethree=4150;
  b.revenuefour=3600;
  b.revenuefive=2600;
  b.revenuesix=2520;
  b.revenueseven=2200;
  b.revenueeight=2100;
  b.revenuenine=1100;
  b.revenueten=600;
  b.countryone=22;
  b.countrytwo=18;
  b.countrythree=70;
  b.countryfour=40;
  b.countryfive=35;
  b.countrysix=10;
  b.countryseven=18;
  b.countryeight=17;
  b.countrynine=21;
  b.countryten=15;
  b.productone=33;
  b.producttwo=30;
  b.productthree=23;
  b.productfour=20;
  b.productfive=19;
  b.productsix=28;
  b.productseven=19;
  b.producteight=18;
  b.productnine=15;
  b.productten=12;
  b.display();
}